---
fontsize: 10pt
geometry: margin=1in
output: pdf_document
---
```{r,message=FALSE,warning=FALSE,echo=FALSE}
library(MASS)
library(knitr)
library(texreg)
setwd("~/Google Drive/WeiweiThesis")

bc.5sites <- read.csv("data/bc.5sites.csv",header = T)

modelfb <- count ~ temperatureMaxSq + temperatureMax + holiday +
  precipProbability+ Wknd + daylight + uw
modeli90 <- I90 ~ temperatureMaxSq + temperatureMax + holiday +
  precipProbability+ Wknd + daylight + uw 
modelbgt <- BGT ~ temperatureMaxSq + temperatureMax + holiday +
  precipProbability+ Wknd + daylight + uw 
modelell <- elliott ~ temperatureMaxSq + temperatureMax + holiday +
  precipProbability+ Wknd + daylight + uw 
modelsb <- Spokanebrdg ~ temperatureMaxSq + temperatureMax + holiday +
  precipProbability+ Wknd + daylight + uw 


mod_fb <- glm(modelfb, data=bc.5sites, family=poisson()) 
mod_bgt <- glm(modelbgt, data=bc.5sites, family=poisson()) 
mod_i90 <- glm(modeli90, data=bc.5sites, family=poisson()) 
mod_ell <- glm(modelell, data=bc.5sites, family=poisson()) 
mod_sb <- glm(modelsb, data=bc.5sites, family=poisson()) 


bc.long <- read.csv("data/bc.long.csv",header = T)
modellong <- bc.count ~  temperatureMaxSq + temperatureMax + holiday +
  precipProbability+ Wknd + daylight + uw +location

mod_long <- glm(modellong, data=bc.long, family=poisson())


result <- cbind(data.frame(coef(mod_fb)),coef(mod_bgt),coef(mod_i90),coef(mod_ell),coef(mod_sb),coef(mod_long)[c(1:8)])

names(result) <-c("fremontb","BGT","elliott","I90","seattleb","5sites")
round(result,digits = 4)
# summary(mod_fb)
# summary(mod_sb)
# summary(mod_ell)
# summary(mod_i90)
# summary(mod_bgt)
# summary(mod_long)
```

```{r, results='asis'}
#2 model summary
texreg(list(mod_fb,mod_sb,mod_ell,mod_i90,mod_bgt),
       caption="Location Comparison",dcolumn=FALSE,caption.above = T,
       custom.coef.names = c("const.","TempMaxSq","TempMax","Holiday","PrecipProb","Weekend",
                             "UW","Daylight"),
       ,custom.model.names =c("Fremont Bridge","Seattle Bridge","Elliott",
                              "I-90","BGT"))
```


